from snakemake.utils import min_version

min_version("9.1.0")


include: "rules/common.smk"
include: "rules/hmmsearch.smk"
include: "rules/cluster_db.smk"
include: "rules/alignment.smk"
include: "rules/build_tree.smk"
include: "rules/cluster_env.smk"

rule all:
    input:
        fn_env_seqs_clust_cat,
