# Locations of data downloads for 
# Metatranscriptome sequences and annotation tables
# and Isolate transcriptomes 
# (isolates sequence files should be the only files in that dir)
dirs_data: 
  metatranscriptomes: /scratch/bgrodner/metaT_data/old_pipeline_chris_parquets
  isolates: data/shiri_isolates

# Path for marferret-marmicrodb database download
path_database: /mnt/nfs/projects/marferret/marmicrodb/MMDB_2024_04_14/MarFERReT.v1.1.1.MARMICRODB.2024_04_14.combined.faa.gz
fn_db_tax: /mnt/nfs/projects/marferret/marmicrodb/MMDB_2024_04_14/MarFERReT.v1.1.1.MARMICRODB.2024_04_14.combined.uid2tax.tab.gz

# Path to scripts
dir_scripts: workflow/scripts

# output dir
dir_out: results

# Path to this config file
fn_config: config/config.yaml

# wildcards to run from metat files
batches:
  - G1NS
  - G1PA
  - G2NS
  - G2PA
  - G3NS
  - G3PA.UW

# Paths to hmmprofiles and associated gene names
fn_gene_info: resources/ko_info_table_type3_sbp.csv


dict_gene_hmmprofile:
  fbp1: resources/fbp1.hmm

# Target taxnames to group things by
ttaxnames:
  - Bacillariophyta
  - Haptophyta
  - Chlorophyta
  - Dinophyceae
  - Pelagomonas

target_genes_for_env_placement:
  - fbp1

# Location to put known crystal structure sequences 
# (should contain only the ones you want to include in the tree building)
dir_rcsb: resources/rcsb_downloads

# could also manually put custom sequences here to be included in the tree
dir_ref_man: resources/manual_references
fn_ref_man_info: resources/manual_references_info.csv

# RCSB ids to download
fn_rcsb_table: resources/rcsb_table_type3_sbp.csv

rcsb_ids:
  - 1ESZ
  - 1K2V
  - 1K7S
  - 3BE5
  - 3BE6


# Resources for rules
get_fasta_from_parquet:
  threads: 16
  mem_mb: 100000
  runtime: 60

hmmsearch:
  thresh_score: 30  # Only keep hits with score greater than or equal to
  threads: 8
  mem_mb: 10000
  runtime: 60

cluster_db_seqs:
  min_seq_id: "0.50" # In quotes for better filenaming
  coverage: "0.75" # In quotes for better filenaming
  cov_mode: 0
  threads: 32
  mem_mb: 100000
  runtime: 60

subset_db_clusts:
  pct: "100"  # in percentage points so to subset 10% give "10"

alignment:
  threads: 16
  mem_mb: 100000
  runtime: 60

trim_alignment_gappy_columns:
  gaps: 0.9
  mode: kpic-gappy
  threads: 4
  mem_mb: 10000
  runtime: 30

filter_alignment:
  frac_thresh: 0.25
  frac_thresh_short_long: 0.9
  threads: 8
  mem_mb: 10000
  runtime: 30

group_env_stuff:
  threads: 4
  mem_mb: 10000
  runtime: 30

cluster_env_hitseqs:
  min_seq_id: "0.90" # In quotes for better filenaming
  coverage: "0.50" # In quotes for better filenaming
  cov_mode: 1
  threads: 1
  mem_mb: 2000
  runtime: 60

build_alignment_hmm:
  threads: 8
  mem_mb: 10000
  runtime: 60

deduplicate_alignment:
  mem_mb: 10000

fasttree_bootstraps:
  n_bootstraps: 100
  threads: 1
  runtime: 30
  mem_mb: 1000

fasttree:
  threads: 8
  mem_mb: 10000
  runtime: 120

roguenarok:
  threads: 8
  mem_mb: 10000
  runtime: 120
  frac_of_improvement_to_use: 0.9  # If removing all of the rogues gives improvement of 1, what fraction of that improvement do you want. Default mode "elbow" finds the elbow of the curve (where diminishing returns start).

build_tree:
  threads: 16
  mem_mb: 10000
  runtime: 2800
  model: PROTGAMMALGF
  n_bootstraps: autoMRE_IGN  # For automatic number of bootstraps use autoMR/autoMRE/autoMRE_IGN

dict_cstrip_val_color: {
  'Substrate':{ # Dark2
      'Hydroxamate siderophore':'#e7298a',
      'Hydroxycarboxylate siderophore':'#d95f02',
      'Catecholate siderophore':'#7570b3',
      'Heme':'#1b9e77',
      'B12':'#66a61e',
      'Iron':'#e6ab02',
      'Zinc':'#a6761d',
      'Manganese':'#666666',
  },
  'Taxon':{ # tab10
      'Bacillariophyta':'#1f77b4',
      'Haptophyta':'#ff7f0e',
      'Chlorophyta':'#2ca02c',
      'Dinophyceae':'#d62728',
      'Actinomycetota':'#9467bd',
      'Bacillota':'#8c564b',
      'Cyanobacteriota':'#e377c2',
      'Pseudomonadota':'#7f7f7f',
      'Bacteria':'#bcbd22',
      'Eukaryota':'#17becf',
      'Archaea':'#222021',
      'Pelagomonas':'#aec7e8',
      'No_taxon_annotation': '#ffffff',
  },
  'Source':{
      'Environmental metatranscriptome':'#b4b4b4',
      'Database':'#ffffff',
      'Crystal structure':'#ffffff',
      'Environmental isolate':'#b4b4b4',
  },
  'Gene':{
      'fbp1':'#000000',
  },
  'Domain':{
      'Eukaryota':'#6930c3',
      'Bacteria':'#80ffdb',
      'Archaea':'#48bfe3',
  }
}